import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Scanner;
import java.util.ArrayList;

public class SavePass {
/*
 * Function Name: generateDatabase
 * Function Prototype: public static
 * Description: returns BST of maps generated by reading a file
 * Parameters: TODO
 * Side Effects: TODO
 * Error Conditions: TODO
 * Return Value: TODO
 */

/*
 * Function Name: saveEntry
 * Function Prototype: public static void saveEntry()
 * Description: function inquires the user for an entry they intend to save.
 * If the entry has already been saved previously, function will ask if user
 * would like to update that entry
 * Parameters: TODO
 * Side Effects: TODO
 * Error Conditions: TODO
 * Return Value: TODO
 */
  public static void saveEntry (){
    //TODO generateDatabase()
    System.out.print("Enter the website/application you intend for: ");
    Scanner scan = new Scanner (System.in);
    String app = scan.nextLine();
    String entry = app.toLowerCase;
    //check if entry was already in system

    //call update entry

    ArrayList<String> value = new ArrayList();
    System.out.print("Enter your username: ");
    String usr = scan.nextLine();

    System.out.print("Enter your password: ");
    String pas = scan.nextLine();

    System.out.println("Would you like to add additional information? [y/n]");
    String ans = scan.nextLine();
    while (ans == y){
      //input additional information
      System.out.

    }

    //call register() to register user
  }

/*
 * Function Name: main
 * Function Prototype: public static  void main (String args[])
 * Description: main driver for SavePass program
 * Parameters: TODO
 * Side Effects: TODO
 * Error Conditions: TODO
 * Return Value: TODO
 */
  public static void main (String args[]){

    //Display options Save/Request
    System.out.println("Choose an option: ");
    System.out.println("1/ Save an entry \n 2/ Request an entry \n 3/Exit");
    switch (in.nextInt()){
      case 1: //save an entry
        saveEntry();
        break;
      case 2: //request an entry
        //TODO requestEntry();
        break;
      case 3: //exit program
        System.exit(0);
        return;
      default:  //invalid option
        System.err.println ("Invalid option");
        break;
    }

  }
}
